[package]
name = "vinequeue"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
crc32fast = "1.4"
snap = "1.1"

[dev-dependencies]
fake = "2.9.2"
